### ISSUE TITLE
AST Formatting

### ISSUE THREAD

**Issue by rocky** [rocky/python-uncompyle6#24]
In an AST display I find it hard to figure out the children of an internal node. This is needed in writing semantic actions. e368ab2 is an attempt to address this.  consider this output

``` 
$ ./bin/uncompyle6 -t test/bytecode_2.5/10_if_else_ternary.pyc
# Python bytecode 2.5 (decompiled from Python 2.6)
# Embedded file name: simple_source/branching/10_if_else_ternary.py
...

(2)  sstmt
   (2)  return_stmt
      (1)  ret_expr
         (1)  expr
            (4)  or
               (1)  expr

                       11       0	LOAD_FAST         'x'
               (1)  jmp_true
                             3	JUMP_IF_TRUE      '27'
               (1)  expr
                  (6)  conditional
                     (1)  expr
                        (1)  cmp
                           (3)  compare
                              (1)  expr
                                            6	LOAD_FAST         'x'
                              (1)  expr
                                            9	LOAD_FAST         'y'
                                        12	COMPARE_OP        '<'
                     (1)  jmp_false
                                  15	JUMP_IF_FALSE     '24'
                     (1)  expr
                                  18	LOAD_FAST         'x'
                               21	JUMP_FORWARD      '27'
                     (1)  expr
                                  24	LOAD_FAST         'y'
                             27_0	COME_FROM         '21'
               (0)  come_from_opt
                27	RETURN_VALUE      ''
             -1	RETURN_LAST       ''
```

The numbers in parens are the counts of the children. So for example `come_from_opt` has no children. While `compare` has 3: `expr`, `expr`, `COMPARE_OP`.

And `conditional` has 6: `expr`, `jmp_false` , `expr`, `JUMP_FORWARD`, `expr`, `COME_FROM`. 

@moagstar  your thoughts?

**Comment by rocky** [comment]
BTW the alignment of `(1) expr` and `27_0 COME_FROM ...` which is the next child after that isn't ideal, but I'm not sure how to easily fix that.

**Comment by moagstar** [comment]
@rocky, I think the child count can be helpful, but I would say that the indentation is probably equally if not more important. How about representing the ast using yaml? I think it would look like this (I knocked this up by hand so perhaps there might be an error):

```yaml
- sstmt:
    - return_stmt:
        - ret_expr:
            - expr:
                - or:
                    - expr:
                        11 0 LOAD_FAST 'x'
                    - jmp_true:
                        3 JUMP_IF_TRUE '27'
                    - expr:
                        - conditional:
                            - expr:
                                - cmp:
                                    - compare:
                                        - expr:
                                            6 LOAD_FAST 'x'
                                        - expr:
                                            9 LOAD_FAST 'y'
                                        - 12 COMPARE_OP '<'
                            - jmp_false:
                                15 JUMP_IF_FALSE '24'
                            - expr:
                                18 LOAD_FAST 'x'
                            - 21 JUMP_FORWARD '27'
                            - expr:
                                 24 LOAD_FAST 'y'
                            - 27_0 COME_FROM '21'
                    - come_from_opt
        - 27 RETURN_VALUE ''
    - -1 RETURN_LAST ''
```

We could even do yaml with child counts (before node node):

```yaml
- (2) sstmt:
    - (2) return_stmt:
        - (1) ret_expr:
            - (1) expr:
                - (4) or:
                    - (1) expr:
                        11 0 LOAD_FAST 'x'
                    - (1) jmp_true:
                        3 null JUMP_IF_TRUE '27'
                    - (1) expr:
                        - (6) conditional:
                            - (1) expr:
                                - (1) cmp:
                                    - (3) compare:
                                        - (1) expr:
                                            6 LOAD_FAST 'x'
                                        - (1) expr:
                                            9 LOAD_FAST 'y'
                                        - 12 COMPARE_OP '<'
                            - (1) jmp_false:
                                15 JUMP_IF_FALSE '24'
                            - (1) expr:
                                18 LOAD_FAST 'x'
                            - 21 JUMP_FORWARD '27'
                            - (1) expr:
                                 24 LOAD_FAST 'y'
                            - 27_0 COME_FROM '21'
                    - come_from_opt
        - 27 RETURN_VALUE ''
    - -1 RETURN_LAST ''
```

Yaml with child counts (after node node):

```yaml
- sstmt (2):
    - return_stmt (2):
        - ret_expr (1):
            - expr (1):
                - or (4):
                    - expr (1):
                        11 0 LOAD_FAST 'x'
                    - jmp_true (1):
                        3 null JUMP_IF_TRUE '27'
                    - expr (1):
                        - conditional (6):
                            - expr (1):
                                - cmp (1):
                                    - compare (3):
                                        - expr (1):
                                            6 LOAD_FAST 'x'
                                        - expr (1):
                                            9 LOAD_FAST 'y'
                                        - 12 COMPARE_OP '<'
                            - jmp_false (1):
                                15 JUMP_IF_FALSE '24'
                            - expr (1):
                                18 LOAD_FAST 'x'
                            - 21 JUMP_FORWARD '27'
                            - expr (1):
                                 24 LOAD_FAST 'y'
                            - 27_0 COME_FROM '21'
                    - come_from_opt
        - 27 RETURN_VALUE ''
    - -1 RETURN_LAST ''
```

What do you think? I have a pretty good idea how this could be done so if you think it's worth implementing I can give it a go.

**Comment by rocky** [comment]
This is fantastic. Would you please make the fix to switch to YAML with the child counts after the node? 

(When you hack pysource.py or fragments.py, there are all those magic child numbers in there).

After that we should also consider updating spark to do this as well.

**Comment by rocky** [comment]
Or how about both my child number and number of children: 

```
...
         - 0. or (4):
                    - 0. expr (1):
                        11 0 LOAD_FAST 'x'
                    - 1. jmp_true (1):
                        3 null JUMP_IF_TRUE '27'
                    - 2 . expr (1):
                            ...
                    - 3. come-from-opt (0):
```

And another variation on this is omitting the child count if it is either 0 or 1 which would be: 

```
...
         - or (4):
                    - 0. expr:
                        11 0 LOAD_FAST 'x'
                    - 1. jmp_true:
                        3 null JUMP_IF_TRUE '27'
                    - 2 . expr:
                            ...
                    - 3. come-from-opt (0):
```

**Comment by moagstar** [comment]
I'll maybe come up with some examples using the various possible representations before we make a final decision on how this should be represented.

**Comment by rocky** [comment]
Again, many thanks. Most people have a better sense of design than I do. So I know that whatever you suggest will be really good.

**Comment by rocky** [comment]
Recently have been tracking down formatting bugs and over in python-spark filling out a much more complete example of using the parsing kit. A better AST formatter is sorely needed.

**Comment by moagstar** [comment]
@rocky I haven't forgotten about this issue, I'm hoping to find some time next week to take a look at getting at least the basic yaml output working - I'll let you know as soon as i have something to show.

**Comment by rocky** [comment]
Many thanks. I appreciate it.

**Comment by moagstar** [comment]
@rocky I have the ast formatting working now, I think this is the best output (with the child number and number of siblings in brackets, omitting if the number of children is less than or equal to one):

```yaml
# Python bytecode 2.5 (decompiled from Python 2.7)
# Embedded file name: simple_source/branching/10_if_else_ternary.py
# Compiled at: 2016-04-07 13:00:07
- stmts:
  - sstmt:
    - stmt:
      - funcdef:
        - mkfunc (1/2):
          - [10, 0, LOAD_CONST, "<code_object minimize>"]
          - [null, 3, MAKE_FUNCTION_0, ]
        - designator (2/2):
          - [null, 6, STORE_NAME, "minimize"]
- stmts:
  - sstmt:
    - return_stmt (1/2):
      - ret_expr (1/2):
        - expr:
          - or:
            - expr (1/4):
              - [11, 0, LOAD_FAST, "x"]
            - jmp_true (2/4):
              - [null, 3, JUMP_IF_TRUE, "27"]
            - expr (3/4):
              - conditional:
                - expr (1/6):
                  - cmp:
                    - compare:
                      - expr (1/3):
                        - [null, 6, LOAD_FAST, "x"]
                      - expr (2/3):
                        - [null, 9, LOAD_FAST, "y"]
                      - [null, 12, COMPARE_OP, "<"]
                - jmp_false (2/6):
                  - [null, 15, JUMP_IF_FALSE, "24"]
                - expr (3/6):
                  - [null, 18, LOAD_FAST, "x"]
                - [null, 21, JUMP_FORWARD, "27"]
                - expr (5/6):
                  - [null, 24, LOAD_FAST, "y"]
                - [null, 27_0, COME_FROM, "21"]
            - come_from_opt (4/4): []
      - [null, 27, RETURN_VALUE, ]
    - [null, -1, RETURN_LAST, ]
```

What do you think?
There is just one small issue to iron out - I added some tests to validate the yaml that is produced and there are a couple which are failing (from the 280 or so which is pretty good). If you like this formatting and once I've got all the tests passing I will make a pull request.

**Comment by moagstar** [comment]
@rocky Oops, I missed the point about the number in the bracket being the number of children, in that case the output looks like this:

```yaml
# Python bytecode 2.5 (decompiled from Python 2.7)
# Embedded file name: simple_source/branching/10_if_else_ternary.py
# Compiled at: 2016-04-07 13:00:07
- stmts:
  - sstmt:
    - stmt:
      - funcdef (2):
        - mkfunc (2):
          - [10, 0, LOAD_CONST, "<code_object minimize>"]
          - [null, 3, MAKE_FUNCTION_0, ]
        - designator:
          - [null, 6, STORE_NAME, "minimize"]
- stmts:
  - sstmt (2):
    - return_stmt (2):
      - ret_expr:
        - expr:
          - or (4):
            - expr:
              - [11, 0, LOAD_FAST, "x"]
            - jmp_true:
              - [null, 3, JUMP_IF_TRUE, "27"]
            - expr:
              - conditional (6):
                - expr:
                  - cmp:
                    - compare (3):
                      - expr:
                        - [null, 6, LOAD_FAST, "x"]
                      - expr:
                        - [null, 9, LOAD_FAST, "y"]
                      - [null, 12, COMPARE_OP, "<"]
                - jmp_false:
                  - [null, 15, JUMP_IF_FALSE, "24"]
                - expr:
                  - [null, 18, LOAD_FAST, "x"]
                - [null, 21, JUMP_FORWARD, "27"]
                - expr:
                  - [null, 24, LOAD_FAST, "y"]
                - [null, 27_0, COME_FROM, "21"]
            - come_from_opt: []
      - [null, 27, RETURN_VALUE, ]
    - [null, -1, RETURN_LAST, ]
```

**Comment by moagstar** [comment]
And once more without any child info...

```yaml
# Python bytecode 2.5 (decompiled from Python 2.7)
# Embedded file name: simple_source/branching/10_if_else_ternary.py
# Compiled at: 2016-04-07 13:00:07
- stmts:
  - sstmt:
    - stmt:
      - funcdef:
        - mkfunc:
          - [10, 0, LOAD_CONST, "<code_object minimize>"]
          - [null, 3, MAKE_FUNCTION_0, ]
        - designator:
          - [null, 6, STORE_NAME, "minimize"]
- stmts:
  - sstmt:
    - return_stmt:
      - ret_expr:
        - expr:
          - or:
            - expr:
              - [11, 0, LOAD_FAST, "x"]
            - jmp_true:
              - [null, 3, JUMP_IF_TRUE, "27"]
            - expr:
              - conditional:
                - expr:
                  - cmp:
                    - compare:
                      - expr:
                        - [null, 6, LOAD_FAST, "x"]
                      - expr:
                        - [null, 9, LOAD_FAST, "y"]
                      - [null, 12, COMPARE_OP, "<"]
                - jmp_false:
                  - [null, 15, JUMP_IF_FALSE, "24"]
                - expr:
                  - [null, 18, LOAD_FAST, "x"]
                - [null, 21, JUMP_FORWARD, "27"]
                - expr:
                  - [null, 24, LOAD_FAST, "y"]
                - [null, 27_0, COME_FROM, "21"]
            - come_from_opt: []
      - [null, 27, RETURN_VALUE, ]
    - [null, -1, RETURN_LAST, ]
```

**Comment by rocky** [comment]
Thanks for doing this.  Some thoughts. 

One purpose is in writing semantic actions, that is why which child number goes with the node is important, and also why knowing how many children there are is important as well. The child number is better done 0 origin since that's how it is used. 

I like in the leaf nodes the leading dash. However for instructions, I think it would be better for leaf nodes (instructions) to look like instructions rather than shown as a list where the first item has "null" when it is not on a line number boundary. 

So for example variations on: 

```
# Python bytecode 2.5 (decompiled from Python 2.7)
# Embedded file name: simple_source/branching/10_if_else_ternary.py
# Compiled at: 2016-04-07 13:00:07
- 0. stmts:
  - sstmt:
    - stmt:
      - funcdef:
        - 0. mkfunc (2):
          - 10     0 LOAD_CONST  <code_object minimize>
          -        3  MAKE_FUNCTION_0
        - 1. designator:
          -        6 STORE_NAME  minimize
- 1. stmts:
  - sstmt:
    - return_stmt:
      - ret_expr:
        - expr:
          - or (2):
            - 0. expr:
              - 11    0 LOAD_FAST  x
            - 1. jmp_true:
              -       3 JUMP_IF_TRUE  27
```
And so on.

**Comment by moagstar** [comment]
@rocky I think we can probably close this issue, your recent changes to the ast formatting have improved things greatly, in fact the main difference between what you did and my latest attempt is the lack of '-' to make it the output look like yaml (I'm unable to make the output valid yaml without making the leaf nodes either a list in [] or a string in "").


For example compare (output from my ast formatting):

```
- stmts:
  - sstmt:
    - stmt:
      - funcdef (2):
        - 0. mkfunc (2):
          - 0. "  10       0  LOAD_CONST        '<code_object minimize>'"
          - 1. "           3  MAKE_FUNCTION_0   ''"
        - 1. designator:
          "           6  STORE_NAME        'minimize'"
- stmts:
  - sstmt (2):
    - 0. return_stmt (2):
      - 0. ret_expr:
        - expr:
          - or (4):
            - 0. expr:
              "  11       0  LOAD_FAST         'x'"
            - 1. jmp_true:
              "           3  JUMP_IF_TRUE      '27'"
            - 2. expr:
              - conditional (6):
                - 0. expr:
                  - cmp:
                    - compare (3):
                      - 0. expr:
                        "           6  LOAD_FAST         'x'"
                      - 1. expr:
                        "           9  LOAD_FAST         'y'"
                      - 2. "          12  COMPARE_OP        '<'"
                - 1. jmp_false:
                  "          15  JUMP_IF_FALSE     '24'"
                - 2. expr:
                  "          18  LOAD_FAST         'x'"
                - 3. "          21  JUMP_FORWARD      '27'"
                - 4. expr:
                  "          24  LOAD_FAST         'y'"
                - 5. "        27_0  COME_FROM         '21'"
            - 3. come_from_opt: []
      - 1. "          27  RETURN_VALUE      ''"
    - 1. "          -1  RETURN_LAST       ''"
```

With (output from your recent commit):

```
stmtsb
    sstmt
        stmt
            funcdef (2)
                 0. mkfunc (2)
                     0.   10       0  LOAD_CONST        '<code_object minimize>'
                     1.            3  MAKE_FUNCTION_0   ''
                 1. designator
                               6  STORE_NAME        'minimize'stmts
    sstmt (2)
         0. return_stmt (2)
             0. ret_expr
                expr
                    or (4)
                         0. expr
                              11       0  LOAD_FAST         'x'
                         1. jmp_true
                                       3  JUMP_IF_TRUE      '27'
                         2. expr
                            conditional (6)
                                 0. expr
                                    cmp
                                        compare (3)
                                             0. expr
                                                           6  LOAD_FAST         'x'
                                             1. expr
                                                           9  LOAD_FAST         'y'
                                             2.           12  COMPARE_OP        '<'
                                 1. jmp_false
                                              15  JUMP_IF_FALSE     '24'
                                 2. expr
                                              18  LOAD_FAST         'x'
                                 3.           21  JUMP_FORWARD      '27'
                                 4. expr
                                              24  LOAD_FAST         'y'
                                 5.         27_0  COME_FROM         '21'
                         3. come_from_opt
             1.           27  RETURN_VALUE      ''
         1.           -1  RETURN_LAST       ''
``` 

What do you think?
